[package]
name = "chip8_emulator"
version = "0.1.0"
authors = ["AndreOGodoy <godoy.andre@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
ggez = "0.5"
sdl2 = "0.34.2"

